[program:convo]  ;程序名称
user=root  ;执行程序的用户
command=/root/workspace/golang/convo/convo  ;执行的命令
directory=/root/workspace/golang/convo ;命令执行的目录
stopsignal=TERM  ;重启时发送的信号
autostart=true
autorestart=true  ;是否自动重启
stdout_logfile=/var/log/convo/convo-stdout.log  ;标准输出日志位置
stderr_logfile=/var/log/convo/convo-stderr.log  ;标准错误日志位置

